# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f91f2d8f-a96f-4acf-911c-4ecdc4794eac";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f91f2d8f-a96f-4acf-911c-4ecdc4794eac".device = "/dev/disk/by-uuid/f91f2d8f-a96f-4acf-911c-4ecdc4794eac";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/974A-E2F1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fb4ec710-f4c0-4a6a-928a-ee3f2f302bee"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
